pipeline:
  
  copy:
    image: appleboy/drone-scp
    host: nicco.io
    username: deploy
    port: 1312
    secrets: [ ssh_key ]
    target: /srv/web/dvb
    source: ./*
    when:
      event: push
      branch: master